name: Setup Node and install deps
description: Checkout repo, setup Node, restore cache, install deps
runs:
  using: composite
  steps:
    - name: Use Node.js from .nvmrc
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
        cache: "npm"

    - name: Restore npm cache
      uses: actions/cache@v5
      with:
        path: ~/.npm
        key: npm-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          npm-${{ runner.os }}-

    - name: Install dependencies
      run: npm ci
      shell: bash
